version: '3'
services:
  api:
    image: mistermur/fwjb-api
    build:
      context: .
      dockerfile: fwjbBackend/Dockerfile.dev
    networks:
      - webappnetwork
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
    - ./:/usr/src/app
  fwjb:
    image: mistermur/fwjb-frontend
    build:
      context: .
      dockerfile: fwjbFrontend/Dockerfile.dev
    links:
      - api
    ports:
        - "3000:3000"
    volumes:
        - /app/node_modules
        - .:/app
    stdin_open: true
    environment:
        - CHOKIDAR_USEPOLLING=true
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
        - ./data-node:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
        - webappnetwork

networks:
  webappnetwork:
    driver: bridge