version: '3'
services:
  api:
    image: mistermur/fwjb-api
    build:
      context: ./fwjbBackend
      dockerfile: Dockerfile.dev

    networks:
      - webappnetwork
    ports:
      - "8080:8080"
    # depends_on:
    #   - mongo
    volumes:
      - /app/node_modules
      - ./fwjbBackend:/usr/src/app
    environment: 
      - MONGODB_URL=mongodb+srv://justin:fwjb@cluster0.ygcot.mongodb.net/fwjb?retryWrites=true&w=majority
      - MONGODB_URI=mongodb+srv://admin:adminadmin@fwjb.u4e1e.mongodb.net/fwjbDB?retryWrites=true&w=majority
      - MONGODB_TEST=mongodb+srv://admin:adminadmin@fwjb.u4e1e.mongodb.net/testfwjbDB?retryWrites=true&w=majority
  fwjb:
    image: mistermur/fwjb-frontend
    build:
      context: ./fwjbFrontend
      dockerfile: Dockerfile.dev
    links:
      - api
    ports:
        - "3000:3000"
    volumes:
        - /app/node_modules
        - ./fwjbFrontend:/app
    stdin_open: true
    environment:
        - CHOKIDAR_USEPOLLING=true
    networks:
      - webappnetwork
  # mongo:
  #   image: mongo
  #   restart: always
  #   container_name: 'fwjbDB'
  #   volumes:
  #       - ./data-node:/data/db
  #   ports:
  #       - 27017:27017
  #   command: mongod --noauth --smallfiles
  #   environment: 
  #     - MONGO_INITDB_DATABASE=fwjb-db
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=adminadmin
  #   networks:
  #       - webappnetwork

networks:
  webappnetwork:
    driver: bridge